version: '3.4'

services:
  rstudiopreview:
    build:
      context: ./rstudio_docker
    container_name: ${RSC_CONTAINER_NAME}
    volumes:
      - ${VOLUME_PATH}:${VOLUME_PATH}
      - /home/${USER}/.ssh:/home/${USER}/.ssh
      - ${RENV_PATHS_CACHE_HOST}:${RENV_PATHS_CACHE_CONTAINER}
      - ${VOLUME_PATH}/.devcontainer/rstudio_config_dir:/home/${USER}/.config/rstudio
    restart:
      unless-stopped
    ports:
      - ${RSC_LOCAL_PORT}:8787
    env_file: .env
  vsc:
    build:
      context: ./vsc_docker
    container_name: ${VSC_CONTAINER_NAME}
    volumes:
      - ${VOLUME_PATH}:${VOLUME_PATH}
      - /home/${USER}/.ssh:/home/${USER}/.ssh
      - ${RENV_PATHS_CACHE_HOST}:${RENV_PATHS_CACHE_CONTAINER}
      - ${VOLUME_PATH}/.devcontainer/vsc_config_dir:/home/${USER}/.config/Code/User
    restart:
      unless-stopped
    ports:
      - ${VSC_LOCAL_PORT}:8788
    env_file: .env

